-- Seed Data for PHO-StudentBased
-- DEVELOPMENT AND AUTOMATED TEST USE ONLY.
-- This file creates known fixture accounts and must never be executed against production.

-- 1. Geography
INSERT INTO COUNTRIES (name, code) VALUES ('Philippines', 'PH');

INSERT INTO REGIONS (name, code, country_id)
SELECT 'Region 6 - Western Visayas', '6', id FROM COUNTRIES WHERE code = 'PH';

INSERT INTO PROVINCES (name, region_id)
SELECT 'Aklan', id FROM REGIONS WHERE code = '6';

INSERT INTO MUNICIPALITIES (name, province_id)
SELECT names.name, p.id
FROM (VALUES ('Altavas'), ('Balete'), ('Banga'), ('Batan'), ('Buruanga'), ('Ibajay'), ('Kalibo'), ('Lezo'), ('Libacao'), ('Madalag'), ('Makato'), ('Malay'), ('Malinao'), ('Nabas'), ('New Washington'), ('Numancia'), ('Tangalan')) AS names(name)
CROSS JOIN PROVINCES p WHERE p.name = 'Aklan';

-- PSA Philippine Standard Geographic Code municipality tables, as of 31 July 2025.
-- Retrieved 2026-09-22. Official names retained (including Andagaw and Bachaw).
-- Attribution: Philippine Statistics Authority, CC BY 4.0.
-- 17 municipalities / 327 barangays. Source URLs below are provenance,
-- not database primary keys. Resolve parents by name within Aklan.
-- Altavas: 14 barangays; https://psa.gov.ph/classification/psgc/barangays/0600401000
-- Balete: 10 barangays; https://psa.gov.ph/classification/psgc/barangays/0600402000
-- Banga: 30 barangays; https://psa.gov.ph/classification/psgc/barangays/0600403000
-- Batan: 20 barangays; https://psa.gov.ph/classification/psgc/barangays/0600404000
-- Buruanga: 15 barangays; https://psa.gov.ph/classification/psgc/barangays/0600405000
-- Ibajay: 35 barangays; https://psa.gov.ph/classification/psgc/barangays/0600406000
-- Kalibo: 16 barangays; https://psa.gov.ph/classification/psgc/barangays/0600407000
-- Lezo: 12 barangays; https://psa.gov.ph/classification/psgc/barangays/0600408000
-- Libacao: 24 barangays; https://psa.gov.ph/classification/psgc/barangays/0600409000
-- Madalag: 25 barangays; https://psa.gov.ph/classification/psgc/barangays/0600410000
-- Makato: 18 barangays; https://psa.gov.ph/classification/psgc/barangays/0600411000
-- Malay: 17 barangays; https://psa.gov.ph/classification/psgc/barangays/0600412000
-- Malinao: 23 barangays; https://psa.gov.ph/classification/psgc/barangays/0600413000
-- Nabas: 20 barangays; https://psa.gov.ph/classification/psgc/barangays/0600414000
-- New Washington: 16 barangays; https://psa.gov.ph/classification/psgc/barangays/0600415000
-- Numancia: 17 barangays; https://psa.gov.ph/classification/psgc/barangays/0600416000
-- Tangalan: 15 barangays; https://psa.gov.ph/classification/psgc/barangays/0600417000
INSERT INTO BARANGAYS (name, municipality_id)
SELECT source.barangay_name,
       (SELECT m.id FROM MUNICIPALITIES m JOIN PROVINCES p ON p.id = m.province_id
        WHERE m.name = source.municipality_name AND p.name = 'Aklan')
FROM (VALUES
    ('Altavas', 'Cabangila'),
    ('Altavas', 'Cabugao'),
    ('Altavas', 'Catmon'),
    ('Altavas', 'Dalipdip'),
    ('Altavas', 'Ginictan'),
    ('Altavas', 'Linayasan'),
    ('Altavas', 'Lumaynay'),
    ('Altavas', 'Lupo'),
    ('Altavas', 'Man-up'),
    ('Altavas', 'Odiong'),
    ('Altavas', 'Poblacion'),
    ('Altavas', 'Quinasay-an'),
    ('Altavas', 'Talon'),
    ('Altavas', 'Tibiao'),
    ('Balete', 'Aranas'),
    ('Balete', 'Arcangel'),
    ('Balete', 'Calizo'),
    ('Balete', 'Cortes'),
    ('Balete', 'Feliciano'),
    ('Balete', 'Fulgencio'),
    ('Balete', 'Guanko'),
    ('Balete', 'Morales'),
    ('Balete', 'Oquendo'),
    ('Balete', 'Poblacion'),
    ('Banga', 'Agbanawan'),
    ('Banga', 'Bacan'),
    ('Banga', 'Badiangan'),
    ('Banga', 'Cerrudo'),
    ('Banga', 'Cupang'),
    ('Banga', 'Daguitan'),
    ('Banga', 'Daja Norte'),
    ('Banga', 'Daja Sur'),
    ('Banga', 'Dingle'),
    ('Banga', 'Jumarap'),
    ('Banga', 'Lapnag'),
    ('Banga', 'Libas'),
    ('Banga', 'Linabuan Sur'),
    ('Banga', 'Mambog'),
    ('Banga', 'Mangan'),
    ('Banga', 'Muguing'),
    ('Banga', 'Pagsanghan'),
    ('Banga', 'Palale'),
    ('Banga', 'Poblacion'),
    ('Banga', 'Polo'),
    ('Banga', 'Polocate'),
    ('Banga', 'San Isidro'),
    ('Banga', 'Sibalew'),
    ('Banga', 'Sigcay'),
    ('Banga', 'Taba-ao'),
    ('Banga', 'Tabayon'),
    ('Banga', 'Tinapuay'),
    ('Banga', 'Torralba'),
    ('Banga', 'Ugsod'),
    ('Banga', 'Venturanza'),
    ('Batan', 'Ambolong'),
    ('Batan', 'Angas'),
    ('Batan', 'Bay-ang'),
    ('Batan', 'Caiyang'),
    ('Batan', 'Cabugao'),
    ('Batan', 'Camaligan'),
    ('Batan', 'Camanci'),
    ('Batan', 'Ipil'),
    ('Batan', 'Lalab'),
    ('Batan', 'Lupit'),
    ('Batan', 'Magpag-ong'),
    ('Batan', 'Magubahay'),
    ('Batan', 'Mambuquiao'),
    ('Batan', 'Man-up'),
    ('Batan', 'Mandong'),
    ('Batan', 'Napti'),
    ('Batan', 'Palay'),
    ('Batan', 'Poblacion'),
    ('Batan', 'Songcolan'),
    ('Batan', 'Tabon'),
    ('Buruanga', 'Alegria'),
    ('Buruanga', 'Bagongbayan'),
    ('Buruanga', 'Balusbos'),
    ('Buruanga', 'Bel-is'),
    ('Buruanga', 'Cabugan'),
    ('Buruanga', 'El Progreso'),
    ('Buruanga', 'Habana'),
    ('Buruanga', 'Katipunan'),
    ('Buruanga', 'Mayapay'),
    ('Buruanga', 'Nazareth'),
    ('Buruanga', 'Panilongan'),
    ('Buruanga', 'Poblacion'),
    ('Buruanga', 'Santander'),
    ('Buruanga', 'Tag-osip'),
    ('Buruanga', 'Tigum'),
    ('Ibajay', 'Agbago'),
    ('Ibajay', 'Agdugayan'),
    ('Ibajay', 'Antipolo'),
    ('Ibajay', 'Aparicio'),
    ('Ibajay', 'Aquino'),
    ('Ibajay', 'Aslum'),
    ('Ibajay', 'Bagacay'),
    ('Ibajay', 'Batuan'),
    ('Ibajay', 'Buenavista'),
    ('Ibajay', 'Bugtongbato'),
    ('Ibajay', 'Cabugao'),
    ('Ibajay', 'Capilijan'),
    ('Ibajay', 'Colongcolong'),
    ('Ibajay', 'Laguinbanwa'),
    ('Ibajay', 'Mabusao'),
    ('Ibajay', 'Malindog'),
    ('Ibajay', 'Maloco'),
    ('Ibajay', 'Mina-a'),
    ('Ibajay', 'Monlaque'),
    ('Ibajay', 'Naile'),
    ('Ibajay', 'Naisud'),
    ('Ibajay', 'Naligusan'),
    ('Ibajay', 'Ondoy'),
    ('Ibajay', 'Poblacion'),
    ('Ibajay', 'Polo'),
    ('Ibajay', 'Regador'),
    ('Ibajay', 'Rivera'),
    ('Ibajay', 'Rizal'),
    ('Ibajay', 'San Isidro'),
    ('Ibajay', 'San Jose'),
    ('Ibajay', 'Sta. Cruz'),
    ('Ibajay', 'Tagbaya'),
    ('Ibajay', 'Tul-ang'),
    ('Ibajay', 'Unat'),
    ('Ibajay', 'Yawan'),
    ('Kalibo', 'Andagaw'),
    ('Kalibo', 'Bachaw Norte'),
    ('Kalibo', 'Bachaw Sur'),
    ('Kalibo', 'Briones'),
    ('Kalibo', 'Buswang New'),
    ('Kalibo', 'Buswang Old'),
    ('Kalibo', 'Caano'),
    ('Kalibo', 'Estancia'),
    ('Kalibo', 'Linabuan Norte'),
    ('Kalibo', 'Mabilo'),
    ('Kalibo', 'Mobo'),
    ('Kalibo', 'Nalook'),
    ('Kalibo', 'Poblacion'),
    ('Kalibo', 'Pook'),
    ('Kalibo', 'Tigayon'),
    ('Kalibo', 'Tinigaw'),
    ('Lezo', 'Agcawilan'),
    ('Lezo', 'Bagto'),
    ('Lezo', 'Bugasongan'),
    ('Lezo', 'Carugdog'),
    ('Lezo', 'Cogon'),
    ('Lezo', 'Ibao'),
    ('Lezo', 'Mina'),
    ('Lezo', 'Poblacion'),
    ('Lezo', 'Sta. Cruz'),
    ('Lezo', 'Sta. Cruz Biga-a'),
    ('Lezo', 'Silakat Nonok'),
    ('Lezo', 'Tayhawan'),
    ('Libacao', 'Agmailig'),
    ('Libacao', 'Alfonso XII'),
    ('Libacao', 'Batobato'),
    ('Libacao', 'Bonza'),
    ('Libacao', 'Calacabian'),
    ('Libacao', 'Calamcan'),
    ('Libacao', 'Can-awan'),
    ('Libacao', 'Casit-an'),
    ('Libacao', 'Dalagsaan'),
    ('Libacao', 'Guadalupe'),
    ('Libacao', 'Janlud'),
    ('Libacao', 'Julita'),
    ('Libacao', 'Luctoga'),
    ('Libacao', 'Magugba'),
    ('Libacao', 'Manika'),
    ('Libacao', 'Ogsip'),
    ('Libacao', 'Ortega'),
    ('Libacao', 'Oyang'),
    ('Libacao', 'Pampango'),
    ('Libacao', 'Pinonoy'),
    ('Libacao', 'Poblacion'),
    ('Libacao', 'Rivera'),
    ('Libacao', 'Rosal'),
    ('Libacao', 'Sibalew'),
    ('Madalag', 'Alaminos'),
    ('Madalag', 'Alas-as'),
    ('Madalag', 'Bacyang'),
    ('Madalag', 'Balactasan'),
    ('Madalag', 'Cabangahan'),
    ('Madalag', 'Cabilawan'),
    ('Madalag', 'Catabana'),
    ('Madalag', 'Dit-Ana'),
    ('Madalag', 'Galicia'),
    ('Madalag', 'Guinatu-an'),
    ('Madalag', 'Logohon'),
    ('Madalag', 'Mamba'),
    ('Madalag', 'Maria Cristina'),
    ('Madalag', 'Medina'),
    ('Madalag', 'Mercedes'),
    ('Madalag', 'Napnot'),
    ('Madalag', 'Pang-Itan'),
    ('Madalag', 'Paningayan'),
    ('Madalag', 'Panipiason'),
    ('Madalag', 'Poblacion'),
    ('Madalag', 'San Jose'),
    ('Madalag', 'Singay'),
    ('Madalag', 'Talangban'),
    ('Madalag', 'Talimagao'),
    ('Madalag', 'Tigbawan'),
    ('Makato', 'Agbalogo'),
    ('Makato', 'Aglucay'),
    ('Makato', 'Alibagon'),
    ('Makato', 'Bagong Barrio'),
    ('Makato', 'Baybay'),
    ('Makato', 'Cabatanga'),
    ('Makato', 'Cajilo'),
    ('Makato', 'Calangcang'),
    ('Makato', 'Calimbajan'),
    ('Makato', 'Castillo'),
    ('Makato', 'Cayangwan'),
    ('Makato', 'Dumga'),
    ('Makato', 'Libang'),
    ('Makato', 'Mantiguib'),
    ('Makato', 'Poblacion'),
    ('Makato', 'Tibiawan'),
    ('Makato', 'Tina'),
    ('Makato', 'Tugas'),
    ('Malay', 'Argao'),
    ('Malay', 'Balabag'),
    ('Malay', 'Balusbus'),
    ('Malay', 'Cabulihan'),
    ('Malay', 'Caticlan'),
    ('Malay', 'Cogon'),
    ('Malay', 'Cubay Norte'),
    ('Malay', 'Cubay Sur'),
    ('Malay', 'Dumlog'),
    ('Malay', 'Manoc-Manoc'),
    ('Malay', 'Naasug'),
    ('Malay', 'Nabaoy'),
    ('Malay', 'Napaan'),
    ('Malay', 'Poblacion'),
    ('Malay', 'San Viray'),
    ('Malay', 'Yapak'),
    ('Malay', 'Motag'),
    ('Malinao', 'Banaybanay'),
    ('Malinao', 'Biga-a'),
    ('Malinao', 'Bulabud'),
    ('Malinao', 'Cabayugan'),
    ('Malinao', 'Capataga'),
    ('Malinao', 'Cogon'),
    ('Malinao', 'Dangcalan'),
    ('Malinao', 'Kinalangay Nuevo'),
    ('Malinao', 'Kinalangay Viejo'),
    ('Malinao', 'Lilo-an'),
    ('Malinao', 'Malandayon'),
    ('Malinao', 'Manhanip'),
    ('Malinao', 'Navitas'),
    ('Malinao', 'Osman'),
    ('Malinao', 'Poblacion'),
    ('Malinao', 'Rosario'),
    ('Malinao', 'San Dimas'),
    ('Malinao', 'San Ramon'),
    ('Malinao', 'San Roque'),
    ('Malinao', 'Sipac'),
    ('Malinao', 'Sugnod'),
    ('Malinao', 'Tambuan'),
    ('Malinao', 'Tigpalas'),
    ('Nabas', 'Alimbo Baybay'),
    ('Nabas', 'Buenasuerte'),
    ('Nabas', 'Buenafortuna'),
    ('Nabas', 'Buenavista'),
    ('Nabas', 'Gibon'),
    ('Nabas', 'Habana'),
    ('Nabas', 'Laserna'),
    ('Nabas', 'Libertad'),
    ('Nabas', 'Magallanes'),
    ('Nabas', 'Matabana'),
    ('Nabas', 'Nagustan'),
    ('Nabas', 'Pawa'),
    ('Nabas', 'Pinatuad'),
    ('Nabas', 'Poblacion'),
    ('Nabas', 'Rizal'),
    ('Nabas', 'Solido'),
    ('Nabas', 'Tagororoc'),
    ('Nabas', 'Toledo'),
    ('Nabas', 'Unidos'),
    ('Nabas', 'Union'),
    ('New Washington', 'Candelaria'),
    ('New Washington', 'Cawayan'),
    ('New Washington', 'Dumaguit'),
    ('New Washington', 'Fatima'),
    ('New Washington', 'Guinbaliwan'),
    ('New Washington', 'Jalas'),
    ('New Washington', 'Jugas'),
    ('New Washington', 'Lawa-an'),
    ('New Washington', 'Mabilo'),
    ('New Washington', 'Mataphao'),
    ('New Washington', 'Ochando'),
    ('New Washington', 'Pinamuk-an'),
    ('New Washington', 'Poblacion'),
    ('New Washington', 'Polo'),
    ('New Washington', 'Puis'),
    ('New Washington', 'Tambak'),
    ('Numancia', 'Albasan'),
    ('Numancia', 'Aliputos'),
    ('Numancia', 'Badio'),
    ('Numancia', 'Bubog'),
    ('Numancia', 'Bulwang'),
    ('Numancia', 'Camanci Norte'),
    ('Numancia', 'Camanci Sur'),
    ('Numancia', 'Dongon East'),
    ('Numancia', 'Dongon West'),
    ('Numancia', 'Joyao-joyao'),
    ('Numancia', 'Laguinbanua East'),
    ('Numancia', 'Laguinbanua West'),
    ('Numancia', 'Marianos'),
    ('Numancia', 'Navitas'),
    ('Numancia', 'Poblacion'),
    ('Numancia', 'Pusiw'),
    ('Numancia', 'Tabangka'),
    ('Tangalan', 'Afga'),
    ('Tangalan', 'Baybay'),
    ('Tangalan', 'Dapdap'),
    ('Tangalan', 'Dumatad'),
    ('Tangalan', 'Jawili'),
    ('Tangalan', 'Lanipga'),
    ('Tangalan', 'Napatag'),
    ('Tangalan', 'Panayakan'),
    ('Tangalan', 'Poblacion'),
    ('Tangalan', 'Pudiot'),
    ('Tangalan', 'Tagas'),
    ('Tangalan', 'Tamalagon'),
    ('Tangalan', 'Tamokoe'),
    ('Tangalan', 'Tondog'),
    ('Tangalan', 'Vivo')
) AS source(municipality_name, barangay_name);

-- 2. Users (Passwords are 'password123' hashed with bcrypt, round 10: $2a$10$X13z0wBOnUqJ.Xo24zI2dOYU2mX6x3K/s5B84y4N3r4zK7Zt0GZ5W)
-- I am inserting an admin, superuser, and a teacher
INSERT INTO USERS (email, password_hash, role, first_name, last_name, is_active) VALUES 
('admin@pho.gov.ph', '$2b$10$BT3iHLjxOkdQ3apKbAhZVuJllbRBZX07SdECFZWDRnma2hzJ0EvUO', 'admin', 'System', 'Admin', true),
('super@pho.gov.ph', '$2b$10$BT3iHLjxOkdQ3apKbAhZVuJllbRBZX07SdECFZWDRnma2hzJ0EvUO', 'superuser', 'PHO', 'Doctor', true),
('teacher@pho.gov.ph', '$2b$10$BT3iHLjxOkdQ3apKbAhZVuJllbRBZX07SdECFZWDRnma2hzJ0EvUO', 'teacher', 'Juan', 'Dela Cruz', true);

-- 3. Sample schools (existing fixtures; Andagao uses PSGC spelling Andagaw).
INSERT INTO SCHOOLS (name, address, barangay_id, district)
SELECT source.name, source.barangay_name || ', Kalibo',
       (SELECT b.id FROM BARANGAYS b
        JOIN MUNICIPALITIES m ON m.id = b.municipality_id
        JOIN PROVINCES p ON p.id = m.province_id
        WHERE b.name = source.barangay_name AND m.name = 'Kalibo' AND p.name = 'Aklan'),
       'District I'
FROM (VALUES
    ('Kalibo Elementary School', 'Poblacion'),
    ('Aklan National High School', 'Andagaw')
) AS source(name, barangay_name);

-- 4. Modules
INSERT INTO MODULES (name, slug, description, sort_order) VALUES
('Patient Information', 'patient-info', 'Basic client registry and animal bite records', 1),
('Oral Health', 'oral-health', 'Routine Preventive Oral Care (RPOC)', 2),
('Deworming', 'deworming', 'Deworming medication tracking', 3),
('Immunization', 'immunization', 'School and community based immunization', 4),
('Vital Signs', 'vital-signs', 'Basic vital signs screening', 5);
